routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\HistoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\TopupController;
use App\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/dashboard', AdminController::class)->names('admin');
    Route::resource('/pengguna', UsersController::class)->names('users');
    Route::resource('/produk', ProductController::class)->names('produk');
    Route::resource('/slider', SliderController::class)->names('slider');
    Route::resource('/kategori', CategoryController::class)->names('kategori');
    Route::resource('/pesanan', OrderController::class)->names('order');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', [LoginController::class, 'logout'])->name('login.logout');
    Route::resource('/profil', ProfileController::class)->names('profile');
    Route::resource('/keranjang', CartController::class)->names('cart');
    Route::post('/barang/{id}', [CartController::class, 'store'])->name('cart.store');
    Route::post('/keranjang/{id}', [CartController::class, 'add'])->name('cart.add');
    Route::post('/keranjang/pay/{id}', [CartController::class, 'update'])->name('cart.update');
    // Route::get('/histori', [HistoryController::class, 'index'])->name('history.index');
    Route::resource('/histori', HistoryController::class)->names('history');
    // Route::get('/histori', [HistoryController::class, 'show'])->name('history.show');
    Route::resource('/topup', TopupController::class)->names('topup');
    // Route::get('/profil/topup', [TopupController::class, 'index'])->name('topup.index');
    Route::post('/profil/topup/{amount}', [TopupController::class, 'buyPackage'])->name('topup.buyPackage');
});

Route::resource('/login', LoginController::class)->names('login');
Route::resource('/daftar', RegisterController::class)->names('register');

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/barang', [HomeController::class, 'list'])->name('products.home');
Route::get('/barang/{id}', [HomeController::class, 'show'])->name('products.show');

Route::get('/error', [ErrorController::class, 'error'])->name('error.error');
Route::get('/cant', [ErrorController::class, 'cant'])->name('error.cant');
Route::get('/inprogress', [ErrorController::class, 'inprogress'])->name('error.inprogress');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table = 'categories';
    protected $guarded = ['id'];

    protected $fillable = [
        'nama_kategori',
        'deskripsi'
    ];

    public function products()
    {
        return $this->hasMany(Product::class, 'id_kategori');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\CategoryDataTable;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(CategoryDataTable $datatable)
    {
        return $datatable->render('pages.admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kategori' => 'required|string|max:255',
            'deskripsi' => 'nullable|string',
        ]);

        Category::create([
            'nama_kategori' => $request->nama_kategori,
            'deskripsi' => $request->deskripsi,
        ]);

        return response()->json(['success' => 'Data berhasil Ditambahkan']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $product = Category::findOrFail($id);
        return response()->json($product);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validator = Validator::make($request->all(), [
            'nama_kategori' => 'required|string|max:255',
            'deskripsi' => 'nullable|string',
        ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()]);
        }

        $data = Category::findOrFail($id);

        $data->nama_kategori = $request->nama_kategori;
        $data->deskripsi = $request->deskripsi;
        $data->save();

        return response()->json(['success' => 'Data berhasil diperbarui']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = Category::findOrFail($id);
        $data->delete();


        return response()->json(['success' => 'Data berhasil dihapus']);
    }
}

resources/views/pages/admin/category/action.blade.php
<div class="d-flex justify-content-center align-items-center gap-2">
    <button data-id="{{ $data->id }}" class="btn btn-warning btn-edit">
        <i class="fas fa-pen fs-2"></i>
    </button>
    &nbsp;
    <button data-id="{{ $data->id }}" class="btn btn-danger btn-delete">
        <i class="fas fa-trash fs-2"></i>
    </button>
</div>

resources/views/pages/admin/category/index.blade.php
@extends('komponen.app-admin')
@section('isi')
    <!-- Content-header -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Halaman Kategori</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
                        <li class="breadcrumb-item active">Kategori</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div><!-- /.content-header -->

    <!-- Main content -->
    <div class="card-body py-4">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex gap-1 mb-3">
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addCategoryModal">
                    <i class="fas fa-plus fs-3 me-2"></i>
                    <span class="ms-2 fs-5">Tambah</span>
                </button>
            </div>
        </div>

        <!-- Modal -->
        @include('pages.admin.category.modal')

        <!-- DataTable -->
        <div class="table-relative">
            {{ $dataTable->table() }}
        </div>
    </div><!-- /.content -->
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    <script type="text/javascript">
        $(function() {
            var table = $('#category-table').DataTable();

            $('#addCategoryForm').on('submit', function(e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    url: '{{ route('kategori.store') }}',
                    method: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function(response) {
                        $('#addCategoryModal').modal('hide');
                        table.ajax.reload();
                        alert(response.success);
                    },
                    error: function(response) {
                        alert('Data Gagal Ditambahkan');
                    }
                });
            });

            $(document).on('click', '.btn-edit', function() {
                var categoryId = $(this).data('id');

                $.ajax({
                    url: '/kategori/' + categoryId + '/edit',
                    method: 'GET',
                    success: function(response) {
                        $('#edit_category_id').val(categoryId);
                        $('#edit_nama_kategori').val(response.nama_kategori);
                        $('#edit_deskripsi').val(response.deskripsi);
                        $('#editCategoryModal').modal('show');
                    },
                    error: function(xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });

            $('#editCategoryForm').on('submit', function(e) {
                e.preventDefault();
                var categoryId = $('#edit_category_id').val();
                var formData = new FormData(this);
                formData.append('_method', 'PUT');

                $.ajax({
                    url: '/kategori/' + categoryId,
                    method: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    headers: {
                        'X-HTTP-Method-Override': 'PUT'
                    },
                    success: function(response) {
                        $('#editCategoryModal').modal('hide');
                        table.ajax.reload();
                        alert(response.success);
                    },
                    error: function(response) {
                        alert('Data Gagal Diubah');
                    }
                });
            });

            $(document).on('click', '.btn-delete', function() {
                var categoryId = $(this).data('id');

                if (confirm('Apakah Anda yakin ingin menghapus kategori ini?')) {
                    $.ajax({
                        url: '/kategori/' + categoryId,
                        method: 'DELETE',
                        data: {
                            _token: '{{ csrf_token() }}'
                        },
                        success: function(response) {
                            alert(response.success);
                            table.ajax.reload();
                        },
                        error: function(xhr, status, error) {
                            console.error(xhr.responseText);
                        }
                    });
                }
            });

            $('#searchBox').on('keyup', function() {
                table.search(this.value).draw();
            });
        });
    </script>
@endpush

resources/views/pages/admin/category/modal.blade.php
<!-- Add Modal -->
<div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategoryModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCategoryModalLabel">Tambah Kategori</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="addCategoryForm" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" id="edit_category_id" name="category_id">
                    <div class="mb-3">
                        <label for="nama_kategori" class="form-label">Nama Kategori<span
                                class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="nama_kategori" name="nama_kategori" required>
                    </div>
                    <div class="mb-3">
                        <label for="deskripsi" class="form-label">Deskripsi</label>
                        <input type="text" class="form-control" id="deskripsi" name="deskripsi">
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal Edit Category -->
<div class="modal fade" id="editCategoryModal" tabindex="-1" aria-labelledby="editCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editCategoryModalLabel">Edit Kategori</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editCategoryForm" action="/kategori/{id}" method="POST" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label for="edit_nama_kategori" class="form-label">Nama Kategori</label>
                        <input type="text" class="form-control" id="edit_nama_kategori" name="nama_kategori" required>
                    </div>
                    <div class="mb-3">
                        <label for="edit_deskripsi" class="form-label">Deskripsi</label>
                        <input type="text" class="form-control" id="edit_deskripsi" name="deskripsi">
                    </div>
                </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> --}}
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>