routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\HistoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\TopupController;
use App\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/dashboard', AdminController::class)->names('admin');
    Route::resource('/pengguna', UsersController::class)->names('users');
    Route::resource('/produk', ProductController::class)->names('produk');
    Route::resource('/slider', SliderController::class)->names('slider');
    Route::resource('/kategori', CategoryController::class)->names('kategori');
    Route::resource('/pesanan', OrderController::class)->names('order');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', [LoginController::class, 'logout'])->name('login.logout');
    Route::resource('/profil', ProfileController::class)->names('profile');
    Route::resource('/keranjang', CartController::class)->names('cart');
    Route::post('/barang/{id}', [CartController::class, 'store'])->name('cart.store');
    Route::post('/keranjang/{id}', [CartController::class, 'add'])->name('cart.add');
    Route::post('/keranjang/pay/{id}', [CartController::class, 'update'])->name('cart.update');
    // Route::get('/histori', [HistoryController::class, 'index'])->name('history.index');
    Route::resource('/histori', HistoryController::class)->names('history');
    // Route::get('/histori', [HistoryController::class, 'show'])->name('history.show');
    Route::resource('/topup', TopupController::class)->names('topup');
    // Route::get('/profil/topup', [TopupController::class, 'index'])->name('topup.index');
    Route::post('/profil/topup/{amount}', [TopupController::class, 'buyPackage'])->name('topup.buyPackage');
});

Route::resource('/login', LoginController::class)->names('login');
Route::resource('/daftar', RegisterController::class)->names('register');

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/barang', [HomeController::class, 'list'])->name('products.home');
Route::get('/barang/{id}', [HomeController::class, 'show'])->name('products.show');

Route::get('/error', [ErrorController::class, 'error'])->name('error.error');
Route::get('/cant', [ErrorController::class, 'cant'])->name('error.cant');
Route::get('/inprogress', [ErrorController::class, 'inprogress'])->name('error.inprogress');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table = 'product';
    protected $guarded = ['id'];

    protected $fillable = [
        'nama_produk',
        'gambar',
        'qty',
        'harga',
        'warna',
        'deskripsi',
        'id_kategori',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'id_kategori');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\DataTables\ProductDataTable;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(ProductDataTable $datatable)
    {
        $categories = Category::all();
        return $datatable->render('pages.admin.product.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_produk' => 'required|string|max:255',
            'gambar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:5120',
            'qty' => 'required|numeric',
            'harga' => 'required|string',
            'warna' => 'required|string',
            'deskripsi' => 'nullable|string',
            'id_kategori' => 'required|exists:categories,id'
        ]);

        if ($request->hasFile('gambar')) {
            $filePath = $request->file('gambar')->store('Product', 'public');
        }

        Product::create([
            'nama_produk' => $request->nama_produk,
            'gambar' => $filePath,
            'qty' => $request->qty,
            'harga' => $request->harga,
            'warna' => $request->warna,
            'deskripsi' => $request->deskripsi,
            'id_kategori' => $request->id_kategori
        ]);

        return response()->json(['success' => 'Data berhasil Ditambahkan']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $product->gambar_url = asset('storage/' . $product->gambar);
        $categories = Category::all();
        return response()->json(['product' => $product, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nama_produk' => 'required|string|max:255',
            'gambar' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:5120',
            'qty' => 'required|numeric',
            'harga' => 'required|string',
            'warna' => 'required|string',
            'deskripsi' => 'nullable|string',
            'id_kategori' => 'required|exists:categories,id'
        ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->first()]);
        }

        $data = Product::findOrFail($id);

        if ($request->hasFile('gambar')) {
            if ($data->gambar) {
                Storage::disk('public')->delete($data->gambar);
            }
            $filePath = $request->file('gambar')->store('Product', 'public');
            $data->gambar = $filePath;
        } else{
            $data->gambar = $data->gambar;
        }

        $data->nama_produk = $request->nama_produk;
        $data->qty = $request->qty;
        $data->harga = $request->harga;
        $data->warna = $request->warna;
        $data->deskripsi = $request->deskripsi;
        $data->id_kategori = $request->id_kategori;
        $data->save();

        return response()->json(['success' => 'Data berhasil diperbarui']);
    }
    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = Product::findOrFail($id);

        if ($data->gambar) {
            Storage::disk('public')->delete($data->gambar);
        }

        $data->delete();


        return response()->json(['success' => 'Data berhasil dihapus']);
    }
}

resources/views/pages/admin/product/action.blade.php
<div class="d-flex justify-content-center align-items-center gap-2">
    <button data-id="{{ $data->id }}" class="btn btn-warning btn-edit">
        <i class="fas fa-pen fs-2"></i>
    </button>
    &nbsp;
    <button data-id="{{ $data->id }}" class="btn btn-danger btn-delete">
        <i class="fas fa-trash fs-2"></i>
    </button>
</div>

resources/views/pages/admin/product/index.blade.php
@extends('komponen.app-admin')
@section('isi')
    <!-- Content-header -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Halaman Produk</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
                        <li class="breadcrumb-item active">Produk</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div><!-- /.content-header -->

    <!-- Main content -->
    <div class="card-body py-4">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex gap-1 mb-3">
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addProductModal">
                    <i class="fas fa-plus fs-3 me-2"></i>
                    <span class="ms-2 fs-5">Tambah</span>
                </button>
            </div>
        </div>

        <!-- Modal -->
        @include('pages.admin.product.modal')

        <!-- DataTable -->
        <div class="table-relative">
            {{ $dataTable->table() }}
        </div>
    </div><!-- /.content -->
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    <script type="text/javascript">
        $(function() {
            var table = $('#product-table').DataTable();

            $('#addProductForm').on('submit', function(e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    url: '{{ route('produk.store') }}',
                    method: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function(response) {
                        $('#addProductModal').modal('hide');
                        table.ajax.reload();
                        alert(response.success);
                    },
                    error: function(response) {
                        if (response.responseJSON && response.responseJSON.errors && response
                            .responseJSON.errors.gambar) {
                            alert(response.responseJSON.errors.gambar[0]);
                        } else {
                            alert('Data Gagal Ditambahkan');
                        }
                    }
                });
            });

            $('#gambar').on('change', function() {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#preview_gambar').attr('src', e.target.result)
                        .show();
                }
                reader.readAsDataURL(this.files[0]);
            });

            $(document).on('click', '.btn-edit', function() {
                var productId = $(this).data('id');

                $.ajax({
                    url: '/produk/' + productId + '/edit',
                    method: 'GET',
                    success: function(response) {
                        $('#edit_product_id').val(productId);
                        $('#edit_nama_produk').val(response.product.nama_produk);
                        $('#edit_preview_gambar').attr('src', response.product.gambar_url).show();
                        $('#edit_gambar').val('');
                        $('#edit_qty').val(response.product.qty);
                        $('#edit_harga').val(response.product.harga);
                        $('#edit_warna').val(response.product.warna);
                        $('#edit_deskripsi').val(response.product.deskripsi);

                        var categories = response.categories;
                        var categoryDropdown = $('#edit_id_kategori');
                        categoryDropdown.empty();
                        $.each(categories, function(index, category) {
                            categoryDropdown.append($('<option>', {
                                value: category.id,
                                text: category.nama_kategori,
                                selected: category.id == response.product
                                    .id_kategori
                            }));
                        });

                        $('#editProductModal').modal('show');
                    },
                    error: function(xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });

            $('#edit_gambar').on('change', function() {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#edit_preview_gambar').attr('src', e.target.result)
                        .show();
                }
                reader.readAsDataURL(this.files[0]);
            });

            $('#editProductForm').on('submit', function(e) {
                e.preventDefault();
                var productId = $('#edit_product_id').val();
                var formData = new FormData(this);
                formData.append('_method', 'PUT');

                $.ajax({
                    url: '/produk/' + productId,
                    method: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    headers: {
                        'X-HTTP-Method-Override': 'PUT'
                    },
                    success: function(response) {
                        $('#editProductModal').modal('hide');
                        table.ajax.reload();
                        alert(response.success);
                    },
                    error: function(response) {
                        if (response.responseJSON && response.responseJSON.errors && response
                            .responseJSON.errors.gambar) {
                            alert(response.responseJSON.errors.gambar[0]);
                        } else {
                            alert('Data Gagal Ditambahkan');
                        }
                    }
                });
            });

            $(document).on('click', '.btn-delete', function() {
                var productId = $(this).data('id');

                if (confirm('Apakah Anda yakin ingin menghapus produk ini?')) {
                    $.ajax({
                        url: '/produk/' + productId,
                        method: 'DELETE',
                        data: {
                            _token: '{{ csrf_token() }}'
                        },
                        success: function(response) {
                            alert(response.success);
                            table.ajax.reload();
                        },
                        error: function(xhr, status, error) {
                            console.error(xhr.responseText);
                        }
                    });
                }
            });

            $('#searchBox').on('keyup', function() {
                table.search(this.value).draw();
            });
        });
    </script>
@endpush

resources/views/pages/admin/product/modal.blade.php
<!-- Add Modal -->
<div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-labelledby="addProductModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addProductModalLabel">Tambah Produk</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="addProductForm" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" id="edit_product_id" name="product_id">
                    <div class="mb-3">
                        <label for="nama_produk" class="form-label">Nama Produk<span
                                class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="nama_produk" name="nama_produk" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_kategori" class="form-label">Kategori<span class="text-danger">*</span></label>
                        <select class="form-control" id="id_kategori" name="id_kategori" required>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->nama_kategori }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        <label for="preview_gambar">Pratinjau Gambar</label>
                        <img id="preview_gambar" src="#" alt="Gambar Produk" class="img-fluid"
                            style="display: none;" />
                    </div>
                    <div class="mb-3">
                        <label for="gambar" class="form-label">Gambar<span class="text-danger">*</span></label>
                        <input type="file" class="form-control" id="gambar" name="gambar" required>
                    </div>
                    <div class="mb-3">
                        <label for="qty" class="form-label">Quantity<span class="text-danger">*</span></label>
                        <input type="number" class="form-control" id="qty" name="qty" required>
                    </div>
                    <div class="mb-3">
                        <label for="harga" class="form-label">Harga Produk<span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="harga" name="harga" required>
                    </div>
                    <div class="mb-3">
                        <label for="warna" class="form-label">Warna Produk<span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="warna" name="warna" required>
                    </div>
                    <div class="mb-3">
                        <label for="deskripsi" class="form-label">Deskripsi</label>
                        <input type="text" class="form-control" id="deskripsi" name="deskripsi">
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal Edit Product -->
<div class="modal fade" id="editProductModal" tabindex="-1" aria-labelledby="editProductModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editProductModalLabel">Edit Product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editProductForm" action="/produk/{id}" method="POST" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    @method('PUT')
                    <input type="hidden" id="edit_product_id" name="product_id">
                    <div class="mb-3">
                        <label for="edit_nama_produk" class="form-label">Nama Produk</label>
                        <input type="text" class="form-control" id="edit_nama_produk" name="nama_produk" required>
                    </div>
                    <div class="mb-3">
                        <label for="edit_id_kategori" class="form-label">Kategori</label>
                        <select class="form-control" id="edit_id_kategori" name="id_kategori" required>
                            <!-- Options akan diisi oleh JavaScript -->
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        <label for="edit_preview_gambar">Pratinjau Gambar</label>
                        <img id="edit_preview_gambar" src="#" alt="Gambar Produk" class="img-fluid" style="display: none;" />
                    </div>
                    <div class="mb-3">
                        <label for="edit_gambar" class="form-label">Gambar</label>
                        <input type="file" class="form-control" id="edit_gambar" name="gambar">
                    </div>
                    <div class="mb-3">
                        <label for="edit_qty" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="edit_qty" name="qty" required>
                    </div>
                    <div class="mb-3">
                        <label for="edit_harga" class="form-label">Harga Produk</label>
                        <input type="text" class="form-control" id="edit_harga" name="harga" required>
                    </div>
                    <div class="mb-3">
                        <label for="edit_warna" class="form-label">Warna Produk</label>
                        <input type="text" class="form-control" id="edit_warna" name="warna" required>
                    </div>
                    <div class="mb-3">
                        <label for="edit_deskripsi" class="form-label">Deskripsi</label>
                        <input type="text" class="form-control" id="edit_deskripsi" name="deskripsi">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>