routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\HistoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\TopupController;
use App\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::resource('/dashboard', AdminController::class)->names('admin');
    Route::resource('/pengguna', UsersController::class)->names('users');
    Route::resource('/produk', ProductController::class)->names('produk');
    Route::resource('/slider', SliderController::class)->names('slider');
    Route::resource('/kategori', CategoryController::class)->names('kategori');
    Route::resource('/pesanan', OrderController::class)->names('order');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', [LoginController::class, 'logout'])->name('login.logout');
    Route::resource('/profil', ProfileController::class)->names('profile');
    Route::resource('/keranjang', CartController::class)->names('cart');
    Route::post('/barang/{id}', [CartController::class, 'store'])->name('cart.store');
    Route::post('/keranjang/{id}', [CartController::class, 'add'])->name('cart.add');
    Route::post('/keranjang/pay/{id}', [CartController::class, 'update'])->name('cart.update');
    // Route::get('/histori', [HistoryController::class, 'index'])->name('history.index');
    Route::resource('/histori', HistoryController::class)->names('history');
    // Route::get('/histori', [HistoryController::class, 'show'])->name('history.show');
    Route::resource('/topup', TopupController::class)->names('topup');
    // Route::get('/profil/topup', [TopupController::class, 'index'])->name('topup.index');
    Route::post('/profil/topup/{amount}', [TopupController::class, 'buyPackage'])->name('topup.buyPackage');
});

Route::resource('/login', LoginController::class)->names('login');
Route::resource('/daftar', RegisterController::class)->names('register');

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/barang', [HomeController::class, 'list'])->name('products.home');
Route::get('/barang/{id}', [HomeController::class, 'show'])->name('products.show');

Route::get('/error', [ErrorController::class, 'error'])->name('error.error');
Route::get('/cant', [ErrorController::class, 'cant'])->name('error.cant');
Route::get('/inprogress', [ErrorController::class, 'inprogress'])->name('error.inprogress');

resources/views/komponen/navbar/admin-navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button">
                <i class="fas fa-bars"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('admin.index') }}" class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('login.logout') }}" class="nav-link">Logout</a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('admin.index') }}" class="brand-link text-center">
        <img src="{{ asset('assets/img/Logo/Remove-LogoWhite1.png') }}" alt="Logo" height="30" width="30">
        <img src="{{ asset('assets/img/Logo/Remove-LogoWhite2.png') }}" alt="Logo" height="30">
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{{ route('admin.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Home</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('users.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Pengguna</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('slider.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>Slider</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('kategori.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>Kategori</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('produk.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-box"></i>
                        <p>Produk</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('order.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>Pesanan</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('history.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-history"></i>
                        <p>Histori</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/komponen/navbar/foot-navbar.blade.php
<footer class="mt-5">
    <div class="footer-container">
        <div class="footer-info">
            <a href="https://maps.app.goo.gl/CnjuuzRcBsFAgWKv7" target="_blank" class="footer-link">
                <p><strong>Alamat:</strong> Jl. Menuju Kenangan Indah No.3, Jember, Jawa Timur</p>
            </a>
            <a href="mailto:trushmebin@gmail.com?subject=Subjek%20Email&body=P,%20hallo%20isi%20egga" target="_blank" class="footer-link">
                <p><strong>Email:</strong> tRushMeBin@gmail.com</p>
            </a>
            <a href="https://wa.me/6282331879753?text=p,%20hallo%20egga" target="_blank" class="footer-link">
                <p><strong>Telepon:</strong> +62 823-3187-9753</p>
            </a>
        </div>
        <div class="footer-social-media">
            <a href="https://www.facebook.com/profile.php?id=100089054325920" target="_blank" class="social-icon"><i class="fab fa-facebook-f"></i></a>
            <a href="https://www.instagram.com/rushbinenterprise/" target="_blank" class="social-icon"><i class="fab fa-instagram"></i></a>
            <a href="https://www.youtube.com/@egasyahrul4430/videos" target="_blank" class="social-icon"><i class="fab fa-youtube"></i></a>
        </div>
    </div>
</footer>

resources/views/komponen/navbar/head-navbar.blade.php
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{{ asset('assets/img/Logo/Remove-LogoWhite1.png') }}" alt="Logo" height="30" width="30">
            <img src="{{ asset('assets/img/Logo/Remove-LogoWhite2.png') }}" alt="Logo" height="30">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon bg-light"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav mx-5">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ route('home') }}"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ route('products.home') }}"><i class="fas fa-boxes"></i> List
                        Produk</a>
                </li>
                @if (Auth::check())
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ route('cart.index') }}"><i
                                class="fas fa-shopping-cart"></i> Keranjang</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ route('profile.index') }}"><i
                                class="fas fa-user-alt"></i> Profil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ route('history.show', '1') }}" class="nav-link">
                            <i class="fas fa-history"></i>Histori</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" aria-current="page" href="{{ route('login.logout') }}"><i
                                class="fas fa-sign-out-alt"></i> Keluar</a>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link text-white" aria-current="page" href="{{ route('login.index') }}"><i
                                class="fas fa-sign-in-alt"></i> Masuk</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ route('register.index') }}"><i
                                class="fas fa-clipboard-list"></i> Daftar</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>